### ISSUE TITLE
Data needs manual refresh to load

### ISSUE THREAD

**Issue by Cptkex82** [Danielhiversen/home_assistant_tibber_data#69]
New prices do not load automatically. Restarting home Assistant loads current data. Is it possible to trigger manual refresh via service?

**Comment by AnonymousRetard** [comment]
Is nothing updating for you or are you just having the same problem as me where the attributes with tomorrows prices didn't update when they should? Because for me all other data seems to be updating continously as it should...

I created a seperate issue for this here: https://github.com/Danielhiversen/home_assistant_tibber_data/issues/70

**Comment by Cptkex82** [comment]
Yes it does seem all the other data is refreshing. Its just the prices. I will +1 your comment instead.
