### ISSUE TITLE
Energy price attribute "Tomorrow" not populating

### ISSUE THREAD

**Issue by AnonymousRetard** [Danielhiversen/home_assistant_tibber_data#70]
Hello!

I just installed this component to my home assistant installation yesterday and today I started looking at some way to calculate at what hour it would be the cheapest to start a job that will use X amount of energy over Y amount of hours using the "Energy price" sensor with all the attributes with price per hour.

At the time of writing this the clock is 17:22 here and the attribute "Tomorrow valid" is still "false" and there's no data in the "Tomorrow" attribute. The data for today looks correct though. The state of this sensor is updating though, not just the attributes. Also other sensors provided by tibber_data seem to be updating.

I looked in the Tibber app and it does have prices for tomorrow (they should arrive after 13:00). I also took a look at https://developer.tibber.com/explorer and there I can also see prices for tomorrow.

Finally I tested restarting home assistant and this seems to have populated the "Tomorrow" data and "Tomorrow valid" is now true instead of false. Shouldn't this happen automatically or is it possible to manually trigger an update without restarting home assistant?

**Comment by Cptkex82** [comment]
+1 for this issue. Prices sensor needs to be manually restarted to work

**Comment by Cptkex82** [comment]
I noticed there is errors on the log regarding this integration, could it be related?

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:496
Integration: Sensor (documentation, issues)
First occurred: 10:14:44 (8 occurrences)
Last logged: 10:14:44

Entity sensor.yearly_consumption_hogrostavagen_5 (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.monthly_consumption_compared_to_last_year_hogrostavagen_5 (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.monthly_cost_with_subsidy_hogrostavagen_5 (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.hogboxen_cost_day_2 (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.hogboxen_cost_month_2 (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by AnonymousRetard** [comment]
Unfortunately I don't think it's related. There's a pull request to fix that one here already: https://github.com/Danielhiversen/home_assistant_tibber_data/pull/55

Although the correct solution to it doesn't seem to be fully worked out yet but either way I'm pretty sure it's not related to this error.

**Comment by Cptkex82** [comment]
Im noticing chatter that Nordpool that is the basis of Tibber prices is also malfunctioning in the same matter. Perhaps its related and the problem isnt this integration

**Comment by AnonymousRetard** [comment]
I dug into the code a little bit and it looks like this integration is trying to update at a random time between 13:15 and 13:30 every day. Perhaps this is sometimes too soon even though tomorrows prices are supposed to be available at 13:00? 

Perhaps something more robust is needed which keeps scheduling updates every I don't know 15, 30, 60 minutes, if tomorrows prices weren't received when expected?

I will try to monitor manually for a while  if tomorrows prices consistently are available from their API after 13:15 every day...
