### ISSUE TITLE
Invalid config after restart

### ISSUE THREAD

**Issue by Chimpepe** [Danielhiversen/home_assistant_tibber_data#83]
I've been getting this error when restarting the Home Assistant for a few weeks now

Is the problem with me or the integration?

![Screenshot 2024-01-31 at 07 06 03](https://github.com/Danielhiversen/home_assistant_tibber_data/assets/8383232/bd59fad9-3560-47a7-802f-8318946879ca)
![Screenshot 2024-01-31 at 07 05 52](https://github.com/Danielhiversen/home_assistant_tibber_data/assets/8383232/66f1ffe1-05a5-409e-9bec-9fd9a2853180)
![Screenshot 2024-01-31 at 07 05 28](https://github.com/Danielhiversen/home_assistant_tibber_data/assets/8383232/6f2ffeac-55c6-4c17-8833-c17fd0ee8912)
![Screenshot 2024-01-31 at 07 05 14](https://github.com/Danielhiversen/home_assistant_tibber_data/assets/8383232/c9fd3b91-e645-4389-b11b-2d2b042ac418)

**Comment by SVH-Powel** [comment]
It is the integration. If you know a little bit of programming, you will find the solution here in the pull requests section.

But I think this is situation I don't like to be in. Tibber Data is not providing me with critical data, but it is still important for me. When integrations like this is not maintained and down for weeks, I start to look for alternatives. Perhaps that is a good thing, because the alternatives is often something that free up the tie to companies like Tibber. When the alternative is implemented and working, I can switch over to someone else like "Vibb" which is cheaper and not loosing anything.

**Comment by FSHelgeland** [comment]
There will be an update soon, when they have tested it properly.

**Comment by Chimpepe** [comment]
@SVH-Powel Thanks for the hint!

**Comment by Danielhiversen** [comment]
Fixed in 0.7.2
